Story_4_Django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('story1.urls')),
    path('', include('Matkul.urls')),
    path('', include('kegiatan.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),

]

urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('home', views.home, name='home'),
    path('', views.index0, name='index0'),
    path('index', views.index, name='index'),
    path('index2', views.index2, name='index2'),
    path('index3', views.index3, name='index3'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [

    path('story9/home', views.story9_home, name='story9_home'),
    path('story9/signup', views.signup, name='story9_signup'),

    path('story9/login', views.login_view, name='story9_login'),
    path('story9/logout', views.logout_view, name='story9_logout'),

 
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2',]

story9/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect

from .forms import SignUpForm


# Create your views here.
def story9_home(request):
    return render(request,'story9/home.html')

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data.get("username")
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username = username, password = raw_password)
            # login(request, user)
            return redirect('/story9/login')
    else:
        form = SignUpForm()
    return render(request, 'story9/signup.html', {'form': form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username = username, password = password)

        if user is not None:
            login(request, user)
            if request.user.is_authenticated:
                username = request.user.username
            
            if request.user.first_name is not None:
                first_name = ", " + request.user.first_name
                return render(request,'story9/home.html', {'username': username, 'first_name':first_name})
            
            return render(request,'story9/home.html', {'username': username})

    else:
        form = AuthenticationForm()
    return render(request, 'story9/login.html', {'form': form})

def logout_view(request):
    logout(request)
    text = "Anda berhasil Log Out"
    return render(request, 'story9/home.html', {"text": text})

story9/templates/story9/home.html
{% extends 'base1.html' %}
{% load static %}

{% block content %}
<body id=background3 style="text-align: center; vertical-align: middle;">

  <br>
  <h1>Story 9</h1>
  <br><br>

  {% if user.is_authenticated %}
    <h2> Halo abang/mba {{ username }} {{ first_name }}</h2>
  {% endif %}

  <h2>{{ text }}</h2>
  <br><br>
  <table style="border-spacing: 20px; width: 50%; text-align: center; vertical-align: middle;" class="center">
  <tbody>
    <tr>
      {% if not user.is_authenticated %}
        <td> <a href="{% url 'story9:story9_signup' %}">Sign Up</a> </td>

        <td> <a href="{% url 'story9:story9_login' %}">Log In</a></td>
      {% endif %}

      {% if user.is_authenticated %}
      <td><a href="{% url 'story9:story9_logout' %}">Log Out</a></td>
      {% endif %}

    </tr>
  </tbody>
  </table>
 
{% endblock %}

story9/templates/story9/login.html
{% extends 'base1.html' %}
{% load static %}

{% block content %}
<body id=background3>

  <h2>Log In</h2>
  <form action = "{% url 'story9:story9_login'  %} "method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Log In">
  </form>

{% endblock %}

story9/templates/story9/logout.html
{% extends 'base1.html' %}
{% load static %}

{% block content %}
<body id=background3>

  <h1>Help me.</h1>
  <br>
  <h2>Go find books.</h2>
  <input id="keyword" placeholder="Enter book's keyword">
  <br><br>

  <table id="daftar_buku">
  </table>
 
{% endblock %}

story9/templates/story9/signup.html
{% extends 'base1.html' %}
{% load static %}

{% block content %}
<body id=background3>

  <h2>Sign up</h2>
  <form method="POST">
    {% csrf_token %}
    
    {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
    {% endfor %}

    <button type="submit">Sign up</button>
  </form>
 
{% endblock %}