Matkul/urls.py
from django.urls import path
from . import views

#app_name = 'Matkul'

urlpatterns = [
    path('matkul', views.matkul_view, name='matkul_view'),
    path('matkul_create', views.matkul_create, name='matkul_create'),
    path('matkul_update/<str:pk>/', views.matkul_update, name='matkul_update'),
    path('matkul_delete/<str:pk>/', views.matkul_delete, name='matkul_delete'),
    path('<slug:slug>/', views.matkul_detail, name="detail"),
    

]

Story_4_Django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('story1.urls')),
    path('', include('Matkul.urls')),
    path('', include('kegiatan.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),

]

urlpatterns += staticfiles_urlpatterns()

kegiatan/urls.py
from django.urls import path
from . import views

#app_name = 'Kegiatan'

urlpatterns = [
    path('kegiatan', views.kegiatan_view, name='kegiatan_view'),
    path('kegiatan_create', views.kegiatan_create, name='kegiatan_create'),
    path('peserta_create/<int:id>', views.peserta_create, name='peserta_create'),
    
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('home', views.home, name='home'),
    path('', views.index0, name='index0'),
    path('index', views.index, name='index'),
    path('index2', views.index2, name='index2'),
    path('index3', views.index3, name='index3'),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('story1/', views.story1, name='story1'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [

    path('story7', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [

    path('story8', views.story8, name='story8'),
    path('story8/data/', views.data_func)
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [

    path('story9/home', views.story9_home, name='story9_home'),
    path('story9/signup', views.signup, name='story9_signup'),

    path('story9/login', views.login_view, name='story9_login'),
    path('story9/logout', views.logout_view, name='story9_logout'),

 
]

Matkul/models.py
import string
import random
from django.db import models
from django.utils.text import slugify

def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))

# Create your models here.
class Matkul(models.Model):
    nama = models.CharField(max_length=100)
    dosen = models.CharField(max_length=100)
    sks = models.IntegerField()
    deskripsi = models.TextField()
    semester = models.CharField(max_length=100)
    ruang = models.IntegerField()

    #slug = models.SlugField()
    slug = models.SlugField(max_length=100, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + "-" + self.nama)
        super(Matkul, self).save(*args, **kwargs)

    def __str__(self):
        return self.nama

main/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

Matkul/forms.py
from django.forms import ModelForm
from .models import Matkul

class MatkulForm(ModelForm):
    class Meta:
        model = Matkul
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'semester', 'ruang']

story9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2',]

Matkul/views.py
from django.shortcuts import render, redirect
from .models import Matkul
from .forms import MatkulForm

# Create your views here.
def matkul_view(request):
    matkuls = Matkul.objects.all().order_by('nama')
    return render(request, 'Matkul/matkul_view.html', {'matkuls':matkuls})

def matkul_create(request):
    form = MatkulForm()
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/matkul')

    return render(request, 'Matkul/matkul_form.html', {'form':form})

def matkul_update(request, pk):

    matkul = Matkul.objects.get(id=pk)
    form = MatkulForm(instance=matkul)

    if request.method == 'POST':
        form = MatkulForm(request.POST, instance=matkul)
        if form.is_valid():
            form.save()
            return redirect('/matkul')

    return render(request, 'Matkul/matkul_form.html', {'form':form})

def matkul_delete(request,pk):
    matkul = Matkul.objects.get(id=pk)
    matkul.delete()
    return redirect('/matkul')


def matkul_detail(request,slug):
    matkul = Matkul.objects.get(slug=slug)
    return render(request, 'Matkul/matkul_detail.html', {'matkul':matkul})

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

def index0(request):
    return render(request, 'main/index0.html')

def index(request):
    return render(request, 'main/index.html')

def index2(request):
    return render(request, 'main/index2.html')

def index3(request):
    return render(request, 'main/index3.html')

story1/views.py
from django.shortcuts import render


def story1(request):
    return render(request, 'story1/story1.html')

story7/views.py
from django.shortcuts import render

# Create your views here.

def story7(request):
    return render(request, 'story7/story7.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.

def data_func(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url )
    data = json.loads(ret.content)
    return JsonResponse(data, safe=False)


def story8(request):
    return render(request, 'story8/story8.html')

story9/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect

from .forms import SignUpForm


# Create your views here.
def story9_home(request):
    return render(request,'story9/home.html')

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data.get("username")
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username = username, password = raw_password)
            # login(request, user)
            return redirect('/story9/login')
    else:
        form = SignUpForm()
    return render(request, 'story9/signup.html', {'form': form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username = username, password = password)

        if user is not None:
            login(request, user)
            if request.user.is_authenticated:
                username = request.user.username
            
            if request.user.first_name is not None:
                first_name = ", " + request.user.first_name
                return render(request,'story9/home.html', {'username': username, 'first_name':first_name})
            
            return render(request,'story9/home.html', {'username': username})

    else:
        form = AuthenticationForm()
    return render(request, 'story9/login.html', {'form': form})

def logout_view(request):
    logout(request)
    text = "Anda berhasil Log Out"
    return render(request, 'story9/home.html', {"text": text})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Gilang M. Bangun</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}

  {%block content2 %}
  {% endblock content2 %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://kit.fontawesome.com/4bd2c18202.js" crossorigin="anonymous"></script>
</body>

</html>

templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Gilang M. Bangun</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <style>
    .upDw{
      width: 10%;
    }

    .accordionTitle {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 50%;
  text-align: left;
  border: none;
  outline: none;
  transition: 0.4s;
  }

  /* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
  .active, .accordion:hover {
    background-color: #ccc;
  }

  /* Style the accordion panel. Note: hidden by default */
  .panel {
    padding: 0 18px;
    background-color: white;
    display: none;
    overflow: hidden;
  }

  table, th, td {
  border: 1px solid black;
  border-collapse: collapse; 
  background-color: white; 
  }
  
  table.center {
  margin-left: auto; 
  margin-right: auto;
}
    
  </style>

  {% block meta %}
  {% endblock meta %}
</head>


  {% block content %}
  {% endblock content %}

  {%block content2 %}
  {% endblock content2 %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="{% static 'js/script.js' %}"></script>
  
  <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> -->
</body>

</html>

templates/navbar.html
<div class="row" id="marginTop3">
    <div class="col-sm-12">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:index' %}">Biodata <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:index2' %}">Skills</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:index3' %}">Education</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'matkul_view' %}">Matkul</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'kegiatan_view' %}">Kegiatan</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'story7:story7' %}">Story7</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'story8:story8' %}">Story8</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'story9:story9_home' %}">Story9</a>
                </li>
         
              </ul>
            </div>
        </nav>
    </div>
</div>